# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
# { config, lib, pkgs, modulesPath, ... }:
{ lib, pkgs, modulesPath, ... }:
{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "ahci" "virtio_pci" "sr_mod" "virtio_blk" ];
    initrd.kernelModules = [ "amdgpu" ];
    kernelModules = [ "kvm-amd" "virtio_gpu" ];
    extraModulePackages = [ ];
    kernelParams = [
      # AMD CPU scaling
      # https://www.kernel.org/doc/html/latest/admin-guide/pm/amd-pstate.html
      # https://wiki.archlinux.org/title/CPU_frequency_scaling#amd_pstate
      # On recent AMD CPUs this can be more energy efficient.
      "amd_pstate=guided"

      # Load amdgpu at stage 1
      "amdgpu"
    ];
  };

  fileSystems = {
    "/" =
      {
        device = "/dev/disk/by-uuid/e1561878-a923-4db9-b920-86952f63640b";
        fsType = "btrfs";
        options = [ "compress=zstd" "subvol=@root" ];
      };

    "/boot" =
      {
        device = "/dev/disk/by-uuid/C9D0-F306";
        fsType = "vfat";
        options = [ "umask=0077" ];
      };

    "/home" =
      {
        device = "/dev/disk/by-uuid/e1561878-a923-4db9-b920-86952f63640b";
        fsType = "btrfs";
        options = [ "compress=zstd" "subvol=@home" ];
      };

    "/nix" =
      {
        device = "/dev/disk/by-uuid/e1561878-a923-4db9-b920-86952f63640b";
        fsType = "btrfs";
        options = [ "compress=zstd" "noatime" "subvol=@nix" ];
      };
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/de184764-4926-457e-b8da-72fe6376909f"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  services.btrfs.autoScrub = {
    enable = true;
    interval = "weekly";
    fileSystems = [ "/" ];
  };

  ## GPU 3D
  services.xserver.videoDrivers = [ "modesetting" ];
  # services.xserver.videoDrivers = [ "amdgpu" ];
  hardware = {
    enableRedistributableFirmware = true;
    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        # ADM ROCm OpenCL runtime
        # rocmPackages.clr
        rocmPackages.clr.icd
        amdvlk
        # Habilite a aceleração de hardware para vídeo (VA-API).
        vaapiVdpau
        libvdpau-va-gl
      ];
      extraPackages32 = with pkgs; [
        driversi686Linux.amdvlk
      ];
    };
    amdgpu = {
      opencl.enable = true;
      initrd.enable = true;
    };
  };

  environment.variables.VDPAU_DRIVER = "va_gl";
  systemd.tmpfiles.rules = [
    "L+    /opt/rocm/hip   -    -    -     -    ${pkgs.rocmPackages.clr}"
  ];
}
